### ISSUE TITLE
ERROR: Error connecting to the database. Error was : 'Cursor' object has no attribute 'cursor'

### ISSUE THREAD

**Issue by MikeDawg** [jkakavas/kippo-pyshield#1]
I'm getting the following error, when executing ./kipposhield.py -db  :

ERROR: Error connecting to the database. Error was : 'Cursor' object has no attribute 'cursor'
INFO: No login attempts found in the specified log source 

I'm trying to track this down in Python myself, but haven't had much luck, yet.

I have populated the following fields:

```
auth_key
dshield_userid
    db_name
    db_host 
    db_username 
    db_password
```

**Comment by jkakavas** [comment]
Hi, thanks for reporting this. I fixed the error, download or git pull the latest version, it should work fine

**Comment by MikeDawg** [comment]
Thanks, works great now!
